export const charSegmentNames = [
	"bubbleBlow",
	"bubblePop",
	"baronVonBlubba",
	"specialBubbles",
	"lightning",
	"fire",
	"extendBubbles",
	"stonerWeapon",
	"drunkAndInvaderWeapon",
	"incendoWeapon",
	"items",
	"largeLightning",
	"bonusRoundCircles",
	"flowingWater",
	"fireOnGround",
	"secretLevelPlatform",
	"secretLevelSideDecor",
	"secretLevelPedestal",
	"secretLevelPedestalRightEdge",
	"secretLevelPedestalDoor",
	"secretLevelBasementDoor",
	"shadows",
] as const;
export type CharSegmentName = (typeof charSegmentNames)[number];
