export const charSegmentNames = [
	"bubbleBlow",
	"bubblePop",
	"baronVonBlubba",
	"specialBubbles",
	"lightning",
	"fire",
	"extendBubbles",
	"stonerWeapon",
	"drunkAndInvaderWeapon",
	"incendoWeapon",
	"items",
	"largeLightning",
	"bonusRoundCircles",
	"flowingWater",
	"fireOnGroundA",
	"fireOnGround",
	"secretLevelPlatform",
	"secretLevelSideDecor",
	"secretLevelPedestal",
	"secretLevelPedestalDoor",
	"secretLevelBasementDoor",
	"shadows",
	"fontHurryUp",
	"fontLevelNumbers5px",
	"fontNumeric",
	"fontFatneck",
	"fontLifeDotLines",
	"fontAlpha",
	"fontPunctuation",
	"fontRuddyHelloThere",
] as const;
export type CharSegmentName = (typeof charSegmentNames)[number];

export const charGroupMeta = {
	bubbleBlow: {
		width: 3,
		height: 2,
		count: 12 * 2,
		hasMask: true,
		transposed: false,
		multicolor: true,
	},
	bubblePop: {
		width: 3,
		height: 2,
		count: 8,
		hasMask: false,
		transposed: false,
		multicolor: true,
	},
	baronVonBlubba: {
		width: 3,
		height: 2,
		count: 4 * 2,
		hasMask: true,
		transposed: false,
		multicolor: true,
	},
	specialBubbles: {
		width: 3,
		height: 2,
		count: 12,
		hasMask: false,
		transposed: false,
		multicolor: true,
	},
	lightning: {
		width: 2,
		height: 2,
		count: 1 * 2,
		hasMask: true,
		transposed: false,
		multicolor: true,
	},
	fire: {
		width: 3,
		height: 2,
		count: 4 * 2,
		hasMask: true,
		transposed: false,
		multicolor: true,
	},
	extendBubbles: {
		width: 3,
		height: 2,
		count: 20,
		hasMask: false,
		transposed: false,
		multicolor: true,
	},
	stonerWeapon: {
		width: 3,
		height: 2,
		count: 2,
		hasMask: false,
		transposed: false,
		multicolor: true,
	},
	drunkAndInvaderWeapon: {
		width: 2,
		height: 2,
		count: 5 * 2,
		hasMask: true,
		transposed: false,
		multicolor: true,
	},
	incendoWeapon: {
		width: 2,
		height: 2,
		count: 4 * 2,
		hasMask: true,
		transposed: false,
		multicolor: true,
	},
	items: {
		width: 2,
		height: 2,
		count: 58,
		hasMask: false,
		transposed: false,
		multicolor: true,
	},
	largeLightning: {
		width: 5,
		height: 2,
		count: 1 * 2,
		hasMask: true,
		transposed: false,
		multicolor: true,
	},
	bonusRoundCircles: {
		width: 2,
		height: 2,
		count: 3,
		hasMask: false,
		transposed: false,
		multicolor: true,
	},
	flowingWater: {
		width: 1,
		height: 1,
		count: 1,
		hasMask: false,
		transposed: false,
		multicolor: true,
	},
	fireOnGroundA: {
		width: 1,
		height: 1,
		count: 1,
		hasMask: false,
		transposed: false,
		multicolor: true,
	},
	fireOnGround: {
		width: 1,
		height: 1,
		count: 2,
		hasMask: false,
		transposed: false,
		multicolor: true,
	},
	secretLevelPlatform: {
		width: 1,
		height: 1,
		count: 1,
		hasMask: false,
		transposed: false,
		multicolor: true,
	},
	secretLevelSideDecor: {
		width: 2,
		height: 2,
		count: 1,
		hasMask: false,
		transposed: true,
		multicolor: true,
	},
	secretLevelPedestal: {
		width: 7,
		height: 1,
		count: 1,
		hasMask: false,
		transposed: false,
		multicolor: true,
	},
	secretLevelPedestalDoor: {
		width: 2,
		height: 2,
		count: 1,
		hasMask: false,
		transposed: false,
		multicolor: true,
	},
	secretLevelBasementDoor: {
		width: 3,
		height: 2,
		count: 1,
		hasMask: false,
		transposed: false,
		multicolor: true,
	},
	shadows: {
		width: 1,
		height: 1,
		count: 6,
		hasMask: false,
		transposed: false,
		multicolor: true,
	},
	fontHurryUp: {
		width: 9,
		height: 1,
		count: 2,
		hasMask: true,
		transposed: false,
		multicolor: true,
	},
	fontLevelNumbers5px: {
		width: 1,
		height: 6,
		count: 1,
		hasMask: false,
		transposed: false,
		multicolor: true,
	},
	fontNumeric: {
		width: 10,
		height: 1,
		count: 1,
		hasMask: false,
		transposed: false,
		multicolor: false,
	},
	fontFatneck: {
		width: 11,
		height: 1,
		count: 1,
		hasMask: false,
		transposed: false,
		multicolor: false,
	},
	fontLifeDotLines: {
		width: 1,
		height: 1,
		count: 2,
		hasMask: false,
		transposed: false,
		multicolor: false,
	},
	fontAlpha: {
		width: 26,
		height: 1,
		count: 1,
		hasMask: false,
		transposed: false,
		multicolor: false,
	},
	fontPunctuation: {
		width: 1,
		height: 1,
		count: 5,
		hasMask: false,
		transposed: false,
		multicolor: false,
	},
	fontRuddyHelloThere: {
		width: 30,
		height: 1,
		count: 1,
		hasMask: false,
		transposed: false,
		multicolor: false,
	},
} as const satisfies Record<
	CharSegmentName,
	{
		readonly width: number;
		readonly height: number;
		readonly count: number;
		readonly hasMask: boolean;
		readonly transposed: boolean;
		readonly multicolor: boolean;
	}
>;
