import { ItemCategoryName } from "../prg/data-locations";

export const itemNames: Record<ItemCategoryName, ReadonlyArray<string>> = {
	points: [
		"eggplant",
		"egg",
		"turnip",
		"peach",
		"onion",
		"carrot",
		"boxnut",
		"purple gem",

		"banana",
		"fries",
		"strawberry",
		"beet",
		"cherries",
		"cake slice",
		"red gem",
		"donut",

		"blue sherbet",
		"orange",
		"tuna sushi", //"ice cream sandwich",
		"ice cream",
		"green locket",
		"beer",
		"burger",
		"icepop",

		"watermelon",
		"white sherbet",
		"red locket",
		"cupcake",
		"chicken",
		"pineapple",
		"yellow sherbet",
		"ramen bowl",

		"cone",
		"persimon",
		"grapes",
		"martini",
		"flan",
		"shrimp sushi",
		"yellow queen",
		"yellow shard",

		"red queen",
		"yellow diamond",
		"green queen",
		"green diamond",
		"purple diamond",
		"chack'n",
		"corn",
	],
	powerups: [
		"shoe",
		"white staff",
		"red staff",
		"yellow candy",
		"purple candy",
		"blue candy",
		"red cross",
		"yellow cross",

		"blue cross",
		"red lamp",
		"yellow lamp",
		"purple lamp",
		"purple ring",
		"red ring",
		"blue ring",
		"clock",

		"green potion",
		"purple potion",
		"yellow potion",
		"green crystal ball",
		"blue umbrella",
		"yellow staff",
		"purple umbrella",
		"blue staff",

		"power heart",
		"yellow box",
		"blue box",
		"white box",
		"green lamp",
		"bomb",
		"purple crystal ball",
		"bell",

		"red door",
		"white door",
		"lightning",
	],
};
