export const spriteGroupNames = [
	"player",
	"bubbleBuster",
	"incendo",
	"colley",
	"hullaballoon",
	"beluga",
	"willyWhistle",
	"stoner",
	"superSocket",
	"playerInBubbleA",
	"playerInBubbleB",
	"bossFacingLeft",
	"bossInBubble",
	"bossFacingRight",
	"bonusCupCake",
	"bonusMelonTopLeft",
	"bonusMelonTopRight",
	"bonusMelonBottom",
	"bonusDiamond",
	"hexagonExplosion",
	"boxyExplosion",
] as const;
export type SpriteGroupName = (typeof spriteGroupNames)[number];
